# Generated by Django 2.1.7 on 2019-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animacionet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emriianimacionit', models.CharField(max_length=100)),
                ('gifi', models.ImageField(upload_to='')),
            ],
        ),
    ]
