# Generated by Django 2.1.7 on 2019-03-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcoders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animacionet',
            name='gifi',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
