# Generated by Django 2.1.7 on 2019-03-28 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jcoders', '0002_auto_20190324_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animacionet',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jcoders.categorite'),
            preserve_default=False,
        ),
    ]
